package main.cl.dagserver.infra.adapters.input.channels.calcite.jdbc;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;

import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.stream.Collectors;

import org.json.JSONArray;
import org.json.JSONObject;

import lombok.extern.log4j.Log4j2;

@SuppressWarnings("unused")
@Log4j2
public class DagJDBCPreparedStatement implements PreparedStatement {

	private DagJDBCConnection connection; 
	private String sql;
	private Integer  resultSetType;
	private Integer  resultSetConcurrency;
	private Integer resultSetHoldability;
	private Integer autoGeneratedKeys;
	private int[] columnIndexes;
	private String[] columnNames;
	
	private Integer maxFieldSize = 0;
	private Integer maxRows = 0;
	private Integer queryTimeout = 5;
	
	private DagJDBCResultSet result = null;
	
	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql, int resultSetType,
			int resultSetConcurrency) {
		log.info("DagJDBCPreparedStatement");
		this.connection = connection;
		this.sql = sql;
		this.resultSetType = resultSetType;
		this.resultSetConcurrency = resultSetConcurrency;
	}

	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability) {
		this.connection = connection;
		this.sql = sql;
		this.resultSetType = resultSetType;
		this.resultSetConcurrency = resultSetConcurrency;
		this.resultSetHoldability = resultSetHoldability;
	}

	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql, int autoGeneratedKeys) {
		this.connection = connection;
		this.sql = sql;
		this.autoGeneratedKeys = autoGeneratedKeys;
	}

	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql, int[] columnIndexes) {
		this.connection = connection;
		this.sql = sql;
		this.columnIndexes = columnIndexes;
	}

	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql, String[] columnNames) {
		this.connection = connection;
		this.sql = sql;
		this.columnNames = columnNames;
	}

	public DagJDBCPreparedStatement(DagJDBCConnection connection, String sql) {
		this.connection = connection;
		this.sql = sql;
	}


	@Override
	public DagJDBCResultSet executeQuery(String sql) throws SQLException {
	    try {
	        this.sql = sql;
	        URL endpoint = new URL(this.connection.getHandler().getNurl());
            HttpURLConnection conn = (HttpURLConnection) endpoint.openConnection();
            conn.setRequestMethod("POST");
	        conn.setRequestProperty("Content-Type", "application/json");
	        this.connection.getHandler().secure(conn);
	        String jsonBody = "{\"sql\":\"" + sql + "\"}";
	        conn.getOutputStream().write(jsonBody.getBytes());
	        int responseCode = conn.getResponseCode();
	        if (responseCode == HttpURLConnection.HTTP_OK) {
	        	var parsed = parseResultSet(conn.getInputStream());
	        	conn.disconnect();
	        	return parsed;
	        } else {
	        	conn.disconnect();
	            throw new SQLException("Failed to execute query. HTTP response code: " + responseCode);
	        }
	    } catch (Exception e) {
	        throw new SQLException("Error executing query: " + e.getMessage(), e);
	    }
	}

	private DagJDBCResultSet parseResultSet(InputStream inputStream) throws SQLException {
	    try {
	        String jsonResponse = new BufferedReader(new InputStreamReader(inputStream))
	                .lines().collect(Collectors.joining("\n"));
	        JSONObject jsonArray = new JSONObject(jsonResponse);
	        var rv = new DagJDBCResultSet(jsonArray.getJSONArray("result"),jsonArray.getJSONArray("metadata"));
	        return rv;
	    } catch (Exception e) {
	        throw new SQLException("Error parsing ResultSet from JSON response", e);
	    }
	}
	@Override
	public int executeUpdate(String sql) throws SQLException {
	    try {
	        this.sql = sql;
	        URL endpoint = new URL(this.connection.getHandler().getNurl());
            HttpURLConnection conn = (HttpURLConnection) endpoint.openConnection();
            conn.setRequestMethod("POST");
	        conn.setDoOutput(true);
	        conn.setRequestProperty("Content-Type", "application/json");
	        this.connection.getHandler().secure(conn);
	        String jsonBody = "{\"sql\":\"" + sql + "\"}";
	        conn.getOutputStream().write(jsonBody.getBytes());

	        int responseCode = conn.getResponseCode();
	        if (responseCode == HttpURLConnection.HTTP_OK) {
	            // Read the response and return the number of affected rows
	            var intv = readUpdateCount(conn.getInputStream());
	            conn.disconnect();
	            return intv;
	        } else {
	            throw new SQLException("Failed to execute update. HTTP response code: " + responseCode);
	        }
	    } catch (Exception e) {
	        throw new SQLException("Error executing update: " + e.getMessage(), e);
	    }
	}

	private int readUpdateCount(InputStream inputStream) throws SQLException {
	    try {
	        String jsonResponse = new BufferedReader(new InputStreamReader(inputStream))
	                .lines().collect(Collectors.joining("\n"));
	        System.out.println(jsonResponse);
	        JSONObject jsonObj = new JSONObject(jsonResponse);
	        var jsonArr = jsonObj.getJSONArray("result");
	        return jsonArr.length();
	    } catch (Exception e) {
	        throw new SQLException("Error reading update count from JSON response", e);
	    }
	}

	@Override
	public void close() throws SQLException {
		
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		return this.maxFieldSize.intValue();
	}

	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		this.maxFieldSize = max;
	}

	@Override
	public int getMaxRows() throws SQLException {
		return this.maxRows.intValue();
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		this.maxRows = max;
	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		throw new SQLFeatureNotSupportedException();
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		return this.queryTimeout;
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		this.queryTimeout = seconds;
	}

	@Override
	public void cancel() throws SQLException {
		
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return null;
	}

	@Override
	public void clearWarnings() throws SQLException {
		
	}

	@Override
	public void setCursorName(String name) throws SQLException {
		
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		if(sql.toLowerCase().startsWith("select")) {
			this.result = this.executeQuery(sql);
			return true;
		} else {
			this.executeUpdate(sql);
			return true;
		}
	}

	@Override
	public DagJDBCResultSet getResultSet() throws SQLException {
		return this.result;
	}

	@Override
	public int getUpdateCount() throws SQLException {
		
		return 0;
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		
		return false;
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		
		
	}

	@Override
	public int getFetchDirection() throws SQLException {
		
		return 0;
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		
		
	}

	@Override
	public int getFetchSize() throws SQLException {
		
		return 0;
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		
		return 0;
	}

	@Override
	public int getResultSetType() throws SQLException {
		
		return 0;
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		
		
	}

	@Override
	public void clearBatch() throws SQLException {
		
		
	}

	@Override
	public int[] executeBatch() throws SQLException {
		
		return null;
	}

	@Override
	public DagJDBCConnection getConnection() throws SQLException {
		return this.connection;
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		
		return false;
	}

	@Override
	public DagJDBCResultSet getGeneratedKeys() throws SQLException {
		
		return null;
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return this.executeUpdate(sql);
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return this.executeUpdate(sql);
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return this.executeUpdate(sql);
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		if(sql.toLowerCase().startsWith("select")) {
			this.result = this.executeQuery(sql);
			return true;
		} else {
			this.executeUpdate(sql);
			return true;
		}
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		if(sql.toLowerCase().startsWith("select")) {
			this.result = this.executeQuery(sql);
			return true;
		} else {
			this.executeUpdate(sql);
			return true;
		}
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		if(sql.toLowerCase().startsWith("select")) {
			this.result = this.executeQuery(sql);
			return true;
		} else {
			this.executeUpdate(sql);
			return true;
		}
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		
		return 0;
	}

	@Override
	public boolean isClosed() throws SQLException {
		
		return false;
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		
		
	}

	@Override
	public boolean isPoolable() throws SQLException {
		
		return false;
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		
		
	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		
		return false;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		
		return null;
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		
		return false;
	}

	@Override
	public DagJDBCResultSet executeQuery() throws SQLException {
		return this.executeQuery(sql);
	}

	@Override
	public int executeUpdate() throws SQLException {
		return this.executeUpdate(sql);
	}

	@Override
	public void setNull(int parameterIndex, int sqlType) throws SQLException {
		
		
	}

	@Override
	public void setBoolean(int parameterIndex, boolean x) throws SQLException {
		
		
	}

	@Override
	public void setByte(int parameterIndex, byte x) throws SQLException {
		
		
	}

	@Override
	public void setShort(int parameterIndex, short x) throws SQLException {
		
		
	}

	@Override
	public void setInt(int parameterIndex, int x) throws SQLException {
		
		
	}

	@Override
	public void setLong(int parameterIndex, long x) throws SQLException {
		
		
	}

	@Override
	public void setFloat(int parameterIndex, float x) throws SQLException {
		
		
	}

	@Override
	public void setDouble(int parameterIndex, double x) throws SQLException {
		
		
	}

	@Override
	public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
		
		
	}

	@Override
	public void setString(int parameterIndex, String x) throws SQLException {
		
		
	}

	@Override
	public void setBytes(int parameterIndex, byte[] x) throws SQLException {
		
		
	}

	@Override
	public void setDate(int parameterIndex, Date x) throws SQLException {
		
		
	}

	@Override
	public void setTime(int parameterIndex, Time x) throws SQLException {
		
		
	}

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
		
		
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
		
		
	}

	@Override
	public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
		
		
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
		
		
	}

	@Override
	public void clearParameters() throws SQLException {
		
		
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
		
		
	}

	@Override
	public void setObject(int parameterIndex, Object x) throws SQLException {
		
		
	}

	@Override
	public boolean execute() throws SQLException {
		if(sql.toLowerCase().startsWith("select")) {
			this.result = this.executeQuery(sql);
			return true;
		} else {
			this.executeUpdate(sql);
			return true;
		}
	}

	@Override
	public void addBatch() throws SQLException {
		
		
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
		
		
	}

	@Override
	public void setRef(int parameterIndex, Ref x) throws SQLException {
		
		
	}

	@Override
	public void setBlob(int parameterIndex, Blob x) throws SQLException {
		
		
	}

	@Override
	public void setClob(int parameterIndex, Clob x) throws SQLException {
		
		
	}

	@Override
	public void setArray(int parameterIndex, Array x) throws SQLException {
		
		
	}

	@Override
	public DagJDBCResultSetMetaData getMetaData() throws SQLException {
		return this.result.getMetaData();
	}

	@Override
	public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
		
		
	}

	@Override
	public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
		
		
	}

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
		
		
	}

	@Override
	public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
		
		
	}

	@Override
	public void setURL(int parameterIndex, URL x) throws SQLException {
		
		
	}

	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException {
		
		return null;
	}

	@Override
	public void setRowId(int parameterIndex, RowId x) throws SQLException {
		
		
	}

	@Override
	public void setNString(int parameterIndex, String value) throws SQLException {
		
		
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
		
		
	}

	@Override
	public void setNClob(int parameterIndex, NClob value) throws SQLException {
		
		
	}

	@Override
	public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
		
		
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
		
		
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
		
		
	}

	@Override
	public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
		
		
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
		
		
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
		
		
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
		
		
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
		
		
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
		
		
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
		
		
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
		
		
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
		
		
	}

	@Override
	public void setClob(int parameterIndex, Reader reader) throws SQLException {
		
		
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
		
		
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader) throws SQLException {
		
		
	}

}
