version: "3.9"  # optional since v1.27.0
services:

  dagserver:
    image: maximolira/dagserver:latest
    container_name: dagserver
    ports:
      - "65002:8080"
      - "65003:2587"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
    - DAGSERVERURI=http://localhost:65002/
    - APP_JDBC_URL=jdbc:mysql://host.docker.internal:65306/scheduler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    - APP_JDBC_USER=scheduler_user
    - APP_JDBC_PASSWORD=password
    - APP_JDBC_DRIVER=com.mysql.cj.jdbc.Driver
    - APP_MIGRATION_JDBC_TYPE=db/migration/mysql
    - APP_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
    volumes:
    - "/home/ec2-user/dags/:/root/dags/"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
