version: "3.9"  # optional since v1.27.0
services:

  dagserver:
    build: .
    container_name: dagserver
    ports:
      - "11000:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
    - "C:/tmp/:/root/dags/"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
volumes:
  my-db: 