version: "3.9"  # optional since v1.27.0
services:

  dagserver:
    build: .
    container_name: dagserver
    environment:
      APP_JDBC_URL: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
      APP_JDBC_USER: sa
      APP_JDBC_PASSWORD: 
      APP_JDBC_DRIVER: org.h2.Driver
      APP_MIGRATION_JDBC_TYPE: classpath:/db/migration/h2
      APP_HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
      APP_EXTENSIONS: jar,txt,xls,xlsx,csv,log,out,sql,jks,db
      APP_PROFILES_DEFAULT: auth-internal,filesystem-memory
      APP_FOLDERPATH:
      KEYCLOAK_HOST:
      KEYCLOAK_REALM:
      KEYCLOAK_CLIENT_ID:
      KEYCLOAK_CLIENT_SECRET:
      APP_USERNAME:
      APP_PWD:
      APP_INIT_API_KEY:
    ports:
      - "11000:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/opt/dags:/root/dags/"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
