name: dagserver-deploy-action
on: [push]
jobs:
  deploy:
    runs-on: [self-hosted]
    name: deploy to aws
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build with test
        run: mvn test
      - name: Analize Sonarcloud
        run: mvn sonar:sonar -Dsonar.projectKey=dagserver -Dsonar.organization=maximolira -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push to docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maximolira/dagserver:latest
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "up -d"